# Generated by Django 4.0.5 on 2022-11-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empId', models.AutoField(primary_key=True, serialize=False)),
                ('eName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('salary', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('empId', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('Confirmpassword', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='SignUp',
        ),
    ]
