# Generated by Django 4.0.5 on 2022-12-01 12:39

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_employee_sign_delete_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_me',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=265)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('email', models.EmailField(error_messages={'invalid_choice': 'you custom error message'}, max_length=100)),
                ('Country', models.CharField(choices=[('dubai', 'DUBAI'), ('seychelles', 'SEYCHELLES'), ('singapore', 'SINGAPORE')], default=None, max_length=15)),
                ('message', models.TextField(max_length=1500)),
            ],
        ),
    ]
